#include <libglademm.h>
#include <gtkmm.h>
#include <map>
#include <string>
#include <vector>
//#include <boost/lexical_cast.hpp>
using Glib::RefPtr;
using Gnome::Glade::Xml;
using std::map;
using std::pair;
using std::string;
using std::vector;
using sigc::bind;
using sigc::mem_fun;
//using boost::lexical_cast;
