const char* menu_xml=
"<ui>"
"	<menubar name=\"MenuBar\">"
"		<menu name=\"FileMenu\" action=\"FileMenuAction\">"
"			<menuitem name=\"New\" action=\"clear-project\"/>"
"			<menuitem name=\"Open...\" action=\"load-project\"/>"
"			<menuitem name=\"Append...\" action=\"append-project\"/>"
"			<menuitem name=\"Import...\" action=\"import-data\"/>"
"			<separator/>"
"			<menuitem name=\"Save\" action=\"save-project\"/>"
"			<menuitem name=\"Save as...\" action=\"save-project-as\"/>"
"			<menuitem name=\"Export...\" action=\"export-image\"/>"
"			<separator/>"
"			<menuitem name=\"Exit\" action=\"exit\"/>"
"		</menu>"
"		<menu name=\"EditMenu\" action=\"EditMenuAction\">"
"			<menuitem name=\"Copy\" action=\"copy-clipboard\"/>"
"			<menuitem name=\"Cut\" action=\"cut-clipboard\"/>"
"			<menuitem name=\"Paste\" action=\"paste-clipboard\"/>"
"			<menuitem name=\"Delete\" action=\"edit-delete\"/>"
"		</menu>"
"		<menu name=\"ViewMenu\" action=\"ViewMenuAction\">"
"			<menu name=\"DetailMenu\" action=\"DetailMenuAction\">"
"				<menuitem name=\"Micro\" action=\"micro-detail\"/>"
"				<menuitem name=\"Tiny\" action=\"tiny-detail\"/>"
"				<menuitem name=\"Low\" action=\"low-detail\"/>"
"				<menuitem name=\"Normal\" action=\"normal-detail\"/>"
"				<menuitem name=\"High\" action=\"high-detail\"/>"
"				<menuitem name=\"Fine\" action=\"fine-detail\"/>"
"				<menuitem name=\"Realistic\" action=\"realistic-detail\"/>"
"				<menuitem name=\"Ultra\" action=\"ultra-detail\"/>"
"			</menu>"
"		</menu>"
"		<menu name=\"HelpMenu\" action=\"HelpMenuAction\">"
"			<menuitem name=\"About...\" action=\"help-about\"/>"
"		</menu>"
"	</menubar>"
"</ui>"
;
