#ifndef EVENTSLIST_H_INCLUDED
#define EVENTSLIST_H_INCLUDED

//Events Identifiers
#define   wsID_FXGEN_PRJ_NEW          wxID_HIGHEST + 1
#define   wsID_FXGEN_PRJ_LOADED       wxID_HIGHEST + 2
#define   wsID_FXGEN_PAGE_CHANGED     wxID_HIGHEST + 3

#define   wsID_FXGEN_OPSEL_CHANGED    wxID_HIGHEST + 10
#define   wsID_FXGEN_OPSHOW_CHANGED   wxID_HIGHEST + 11

//Events Types
BEGIN_DECLARE_EVENT_TYPES()
  DECLARE_EVENT_TYPE(wxEVT_FXGEN_PROJECT, wxID_ANY)
  DECLARE_EVENT_TYPE(wxEVT_FXGEN_OPERATORSCTRL, wxID_ANY)
END_DECLARE_EVENT_TYPES()

//Externals
extern const wxEventType wxEVT_FXGEN_PROJECT;
extern const wxEventType wxEVT_FXGEN_OPERATORSCTRL;


#endif // EVENTSLIST_H_INCLUDED
